Repository OSLL/tello-dev, pull requests merged in 2024-04, with the labels that each got.

#49 Little Changes
  swarm/scripts/solutions/following/config.py
  swarm/scripts/solutions/following/follow_marker_coords.py
  swarm/scripts/solutions/following/state.py
Labels: bug

#52 delete_interface
  delete_interface.py
Labels: dev

#50 Bug fixed
  run_singel_drone.py
  swarm/scripts/solutions/following/config.py
  swarm/scripts/solutions/following/follow_marker_coords.py
Labels: bug

#53 Исправление подключения
  rtl_device/connect.py
  rtl_device/networks.json
  swarm/Dockerfile.networking
  swarm/Dockerfile.swarm_node
  swarm/docker-compose.yml
  swarm/networks.json
  swarm/scripts/networking/localtime
  swarm/scripts/networking/networking.py
Labels: enhancement

#56 Rpc
  requirements.txt
  swarm/Dockerfile.swarm_node
  swarm/Dockerfile.swarm_server
  swarm/docker-compose.yml
  swarm/scripts/rpc/client.py
  swarm/scripts/rpc/server.py
  swarm/scripts/rpc/swarm_server.py
  wiki/swarm.md
Labels: documentation, enhancement, dev

#58 fixed client app
  swarm/scripts/rpc/client.py
  swarm/scripts/rpc/swarm_server.py
Labels: bug, dev

#59 control of a single drone without approach
  swarm/scripts/solutions/following/swarm_controlls.py
Labels: dev
